# Generated by Django 3.0.2 on 2020-03-07 17:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200226_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page', 'verbose_name_plural': 'Contact Pages'},
        ),
        migrations.RenameField(
            model_name='contactpage',
            old_name='intro',
            new_name='intro_en',
        ),
        migrations.RenameField(
            model_name='contactpage',
            old_name='thank_you_text',
            new_name='thank_you_text_en',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_en_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_en_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_ro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_ro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_ro_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text_en_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text_en_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text_ro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text_ro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text_ro_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
