# Generated by Django 3.0.2 on 2020-03-07 17:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200307_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='intro_en_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='intro_en_ro',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='intro_ro_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='intro_ro_ro',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text_en_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text_en_ro',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text_ro_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text_ro_ro',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='intro_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text_ro',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
