# Generated by Django 3.0.2 on 2020-03-08 15:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200307_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.CharBlock(help_text='Add email address', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_lenght=100, required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('phone', wagtail.core.blocks.CharBlock(max_lenght=20, required=True)), ('email', wagtail.core.blocks.CharBlock(max_length=50, required=True))])))]))], default='test'),
            preserve_default=False,
        ),
    ]
