# Generated by Django 3.0.2 on 2020-03-08 15:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=wagtail.core.fields.StreamField([('team_block', wagtail.core.blocks.StructBlock([('email', wagtail.core.blocks.CharBlock(help_text='Add email address', required=True))]))], blank=True, default=[], null=True),
        ),
    ]
