# Generated by Django 3.0.2 on 2020-02-22 12:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Terms Page',
                'verbose_name_plural': 'Terms Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
