# Generated by Django 3.0.2 on 2020-03-07 20:26

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termspage',
            name='content_en',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='termspage',
            name='content_ro',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='termspage',
            name='page_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='termspage',
            name='page_title_ro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
