# Generated by Django 3.0.2 on 2020-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
