# Generated by Django 3.0.2 on 2020-03-08 12:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0002_homepage_banner_title_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title',
            new_name='main_title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title_en',
            new_name='main_title_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('main_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('subtitle', wagtail.core.blocks.TextBlock(help_text='Add subtitle text', required=True))]))], blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_subtitle_ro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title_ro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
