# Generated by Django 3.0.2 on 2020-03-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200308_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='main_image',
            new_name='hero_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='main_subtitle',
            new_name='hero_subtitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='main_title',
            new_name='hero_title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='main_title_en',
            new_name='hero_title_en',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='main_title_ro',
            new_name='hero_title_ro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='main_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='main_subtitle_ro',
        ),
    ]
