# Generated by Django 3.0.2 on 2020-03-08 14:49

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200308_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_horizontal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='background_vertical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('main_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('subtitle', wagtail.core.blocks.TextBlock(help_text='Add subtitle text', required=True))]))], blank=True, default=[], null=True),
        ),
    ]
