# Generated by Django 3.0.2 on 2020-02-23 15:19

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=wagtail.core.fields.RichTextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subtitle',
            field=wagtail.core.fields.RichTextField(default='Test'),
            preserve_default=False,
        ),
    ]
