# Generated by Django 3.0.2 on 2020-03-06 17:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200223_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='subtitle',
            new_name='subtitle_en',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content_ro',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle_ro',
            field=wagtail.core.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
    ]
