# Generated by Django 3.0.2 on 2020-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_globalsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='site_name',
            new_name='site_title',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='site_title_suffix',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
