# Generated by Django 3.0.2 on 2020-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='link_title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link_title_ro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
